---

- hosts: all
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Facts
    local_unix_users_with_ad_logon_facts_generate: true

    # Reports
    local_unix_users_with_ad_logon_reports_generate: true
    local_unix_users_with_ad_logon_reports_backup: false

  roles:
    - name: oneidentity.authentication_services.local_unix_users_with_ad_logon

