- name: copy packages
  hosts: all

  tasks: 
	- name: run some command  
	  command: "ls -al /"

  tasks:
  - name: first task
    ansible.builtin.copy:
      src: /tmp/client/aix-61
      dest: /tmp/
