- name: copy packages
  hosts: all
  become: false

  tasks: 
 
  - name: run some command  
    command: "ls -Al /mnt1"
    delegate_to: localhost

  - name: run some command  
    command: "ls -Al /runner/project"
    delegate_to: localhost

  - name: run some command  
    command: "touch /mnt1/hello.txt"
    delegate_to: localhost


  - name: run some command  
    command: "pwd"
    delegate_to: localhost


  - name: first task
    ansible.builtin.copy:
      src: ./client/linux-x86_64
      dest: /tmp/
