---

- hosts: all 
  become: yes

  # The variables you would most likely want/need to override have been included
  vars:

    # Software states
    client_sw_pkg_state:
      vasclnt: present
      # vasclnts: check 
      vasgp: absent 
      # vasgps: check 
      vassc: absent
      # vascert: check
      # dnsupdate: check 
      # pamdefender: present
      # vasyp: check 
      # vasqa: check 
      # vasproxy: check 
      # vasdev: check 

    # Facts
    client_sw_facts_generate: true
    client_sw_facts_verbose: false 
    
    # Reports
    client_sw_reports_generate: true 
    client_sw_reports_backup: false 

  roles:
    - name: oneidentity.authentication_services.client_sw
