- name: copy packages
  hosts: all
  become: false

  tasks: 
 
  - name: ls /  
    command: "ls -Al /"
    delegate_to: localhost

  - name: ls mnt1  
    command: "ls -Al /mnt1"
    delegate_to: localhost

  - name: get hostname  
    command: "cat /etc/hostname"
    delegate_to: localhost
  
  - name: get mount hostname  
    command: "cat /mnt1/etc/hostname"
    delegate_to: localhost


  - name: first task
    ansible.builtin.copy:
      src: ./client/linux-x86_64/preflight
      dest: /mnt2
