- name: copy packages
  hosts: all

  tasks: 
  - name: run some command  
    command: "ls -al /tmp"

  - name: first task
    ansible.builtin.copy:
      src: /var/lib/awx/projects/client
      dest: /tmp/
